import Head from 'next/head'
import Menu from '../components/menu'
import '../styles/globals.css'
import '../styles/style.scss'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>I2BIO – Instituto de Bioinformática e Biotecnologia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Menu />

      <Component {...pageProps} />
    </>
  )
}

export default MyApp
